apiVersion: apps/v1
kind: deployment
metadata:
  name: app-html-deployment
  labels:
    app: app-html
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: app-html
    template:
      metadata:
        labels:
          app: app-html
      spec:
        containers:
        - name: app-html
          image: httpd:latest
          ports:
          - containersPort: 80
